services:
  - type: web
    name: jyoti-software-company
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    # Render health check (change to /actuator/health if you added Actuator)
    healthCheckPath: /home

    # Optional: build only when these paths change
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - JyotiSoftware_pvt_ltd/**

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://switchyard.proxy.rlwy.net:36188/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: LsZxBqitFmFrzmtgItFwlgOZZtnyeTqn
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQL8Dialect
